POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjZjOGJkZTc1OTczN2YzN2UzOWQ5N2UyIiwiaWF0IjoxNzI0NDMzMjkyfQ.E85GjhobsN_zUU2SsC7bs9mflnxA-PZr2hLRXTwnzUA

{
    "title": "Comment configurer et utiliser efficacement l’historique bash",
    "author": "Alexis Madrzejewski",
    "url": "https://blog.madrzejewski.com/astuce-historique-bash-linux/",
    "likes": 0
}